### ISSUE TITLE
Set ggplot2 colors to match CSS

### ISSUE THREAD

**Issue by juliasilge** [EmilHvitfeldt/smltar#74]
It is [now much easier to set colors for ggplot2](https://twitter.com/yutannihilat_en/status/1287402204987396096), so let's take some of the colors from the CSS by Desirée and make the plots match.

**Comment by juliasilge** [comment]
Use [thematic](https://rstudio.github.io/thematic/) to make colors for plots

**Comment by juliasilge** [comment]
I tried using thematic and it might not be quite mature enough for us to use right now. I set some defaults in 99654755abf67b702c10cb7da8bb9e6c9bc684dd so that should be a start. I think the thing to consider adding still is maybe a non-default discrete scale, if we want.

**Comment by EmilHvitfeldt** [comment]
What do you think of defaulting to the following palettes for discrete and continuous color scales? (we don't need to use {paletteer}, just an easy way to visualize palettes) The discrete palette is hard to find since we are using up to 10 colors at once like [here](https://smltar.com/mlregression.html#firstregressionevaluation).

``` r
library(paletteer)
plot(paletteer_d("RColorBrewer::Set3"))
```

![](https://i.imgur.com/poGc5uk.png)

``` r
plot(paletteer_c("viridis::viridis", 100))
```

![](https://i.imgur.com/2YGfQ1r.png)

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
